POST https://khoa-online.herokuapp.com/add_origin HTTP/1.1
Content-Type: application/json

{
    "domain":"http://45.118.145.201"
}
###
POST https://khoa-online.herokuapp.com/delete_origin HTTP/1.1
Content-Type: application/json

{
   "_id": "620fc503a9ad583f6a7df393",
    "domain": "http://45.118.145.204"
}

###
GET https://khoa-online.herokuapp.com/getall_origin HTTP/1.1
content-type: application/json

###
POST https://khoa-online.herokuapp.com/check_origin HTTP/1.1
Content-Type: application/json

{
    "domain": "http://45.118.145.204"
}